name: build-deploy-pr
on:
  pull_request:
jobs:
  deploy-images:
    runs-on: ubuntu-latest
    env:
      registry: docker
      username: degauss-org
      repository: jfs_aggreggated_data_report
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create latest tag variable
        run: |
          container="${{ env.registry }}/${{ env.username}}/${{ env.repository }}:latest"
          echo "container=${container}" >> $GITHUB_ENV
      - name: create pull request tag variable based on name of associated branch
        if: github.event_name == 'pull_request'
        run: |
          versioned="${{ env.registry }}/${{ env.username}}/${{ env.repository }}:${GITHUB_HEAD_REF}"
          echo "versioned=${versioned}" >> $GITHUB_ENV
      - name: build container
        run: |
          docker build -t ${{ env.container }} .
      - name: test run container
        run: |
          docker run --rm -v "${PWD}/test":/tmp ${{ env.container }} sim_test_data_new_prepped_geocoder_3.3.0_score_threshold_0.5_census_block_group_0.6.0_2010.csv

